//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_wristhud : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean wristtoggle
        {
            get
            {
                return SteamVR_Actions.wristhud_wristtoggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean wristleft
        {
            get
            {
                return SteamVR_Actions.wristhud_wristleft;
            }
        }
        
        public virtual SteamVR_Action_Boolean wristright
        {
            get
            {
                return SteamVR_Actions.wristhud_wristright;
            }
        }
        
        public virtual SteamVR_Action_Boolean wristconfirm
        {
            get
            {
                return SteamVR_Actions.wristhud_wristconfirm;
            }
        }
    }
}
